# Generated by Django 3.2.6 on 2021-09-06 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ('name',)},
        ),
    ]
