# Generated by Django 3.2.6 on 2021-09-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_trip_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ('-name',)},
        ),
        migrations.RemoveField(
            model_name='expenditure',
            name='hq',
        ),
        migrations.RemoveField(
            model_name='expenditure',
            name='office',
        ),
        migrations.AddField(
            model_name='expenditure',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
