# Generated by Django 3.2.6 on 2021-09-06 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_pv_pv_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='pv',
            name='account_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.account_code'),
        ),
    ]
