# Generated by Django 3.2.6 on 2021-09-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_pv_account_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='pv',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
