# Generated by Django 3.2.6 on 2021-09-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_pv_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pv_details',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
