# Generated by Django 3.2.6 on 2021-09-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_pv_details_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pv',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled')], max_length=15),
        ),
    ]
