# Generated by Django 3.2.6 on 2021-09-07 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_alter_pv_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pv',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.trip'),
        ),
    ]
