# Generated by Django 3.2.6 on 2021-09-07 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_pv_trip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_account',
            new_name='is_manager',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='is_admin',
            new_name='is_standard',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_bakery',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_bank',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_director',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_irishgreen',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_parent',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_partytree',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_principal',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_staff',
        ),
    ]
