# Generated by Django 3.2.6 on 2021-09-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_auto_20210907_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
