# Generated by Django 3.2.6 on 2021-09-18 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.trip'),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.order'),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.trip'),
        ),
    ]
