# Generated by Django 3.2.6 on 2021-09-29 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_auto_20210918_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.order'),
        ),
    ]
